name: styles_pkg
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: yury.yufimov <yury.yufimov@team.wrike.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dev_dependencies:
  less_dart: any
