name: main_pkg
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: yury.yufimov <yury.yufimov@team.wrike.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  less_dart: 2.3.3
